backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "home"
    label: "Página Inicial"
    files:
      - label: "Conteúdo da Home"
        name: "home"
        file: "data/home.json"
        fields:
          - { label: "Título Principal", name: "hero_titulo", widget: "string" }
          - { label: "Descrição", name: "hero_descricao", widget: "text" }
          - { label: "WhatsApp (só números)", name: "whatsapp", widget: "string" }
          - { label: "Imagem de Fundo", name: "hero_imagem", widget: "image" }
