backend:
  name: github
  repo: andreluiz05/semearfitness
  branch: main
  base_url: https://semearfitness.com.br
  auth_endpoint: /admin/oauth

site_url: https://dainty-malasada-e77663.netlify.app
display_url: https://semearfitness.com.br

media_folder: "/"
public_folder: "/"

collections:
  - name: home
    label: "Página Inicial"
    files:
      - label: "Home"
        name: home
        file: "data/home.yml"
        fields:
          - { label: "Título do Hero", name: "hero_titulo", widget: "string" }
          - { label: "Descrição do Hero", name: "hero_descricao", widget: "text" }
          - { label: "Slogan", name: "hero_slogan", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - { label: "Imagem do Hero", name: "hero_imagem", widget: "image" }
          - { label: "Imagem dos Planos", name: "imagem_planos", widget: "image" }
